"""Immutable file, image and helper inputs shared by public and CI preparation."""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import platform
import struct
import subprocess
import sys
import tarfile
import tempfile
import importlib.util

_spec = importlib.util.spec_from_file_location('demo_wheels', Path(__file__).with_name('demo_wheels.py'))
demo_wheels = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(demo_wheels)

HELPERS = {
    "zot": "ZOT_BIN", "versitygw": "VGW_BIN", "custom-proxy": "CUSTOM_PROXY_BIN",
    "telemetry-grpc-probe": "TELEMETRY_GRPC_PROBE_BIN", "usage-probe": "USAGE_PROBE_BIN",
    "cgroup-fork-probe": "CGROUP_FORK_PROBE_BIN",
}
IMAGE_VARIABLES = {
    "prometheus": "TELEMETRY_PROMETHEUS_IMAGE", "clickhouse": "TELEMETRY_CLICKHOUSE_IMAGE",
    "orchestrator-base": "ORCHESTRATOR_BASE_IMAGE", "orchestrator-execute": "ORCHESTRATOR_EXECUTE_IMAGE",
    "busybox": "KUASAR_BUSYBOX_IMAGE",
}
BACKENDS = {
    "prometheus": "prom/prometheus:v3.5.0@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996",
    "clickhouse": "clickhouse/clickhouse-server:25.8@sha256:0152dd511befe6a2c2ef53e930726179669b08116da78500b37c51c96ff5ee77",
}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(path):
    with Path(path).open('rb') as data:
        return hashlib.file_digest(data, 'sha256').hexdigest()


def check_helper(path, arch):
    require(path.is_file() and not path.is_symlink(), 'missing prebuilt helper file')
    mode = path.stat().st_mode
    require(mode & 0o111 and not mode & 0o7022, 'unsafe or non-executable helper')
    with path.open('rb') as stream:
        header = stream.read(64)
    require(len(header) == 64 and header[:7] == b'\x7fELF\x02\x01\x01' and
            struct.unpack_from('<H', header, 18)[0] == {'x86_64': 62, 'aarch64': 183}[arch],
            'prebuilt helper has the wrong architecture')


def files(root):
    require(root.is_dir() and not root.is_symlink(), f'missing input directory: {root}')
    result = {}
    for path in sorted(root.rglob('*')):
        require(not path.is_symlink(), f'symlink in prepared inputs: {path}')
        if path.is_dir():
            continue
        require(path.is_file(), f'non-regular prepared input: {path}')
        result[str(path.relative_to(root))] = digest(path)
    return result


def seal(root, provenance):
    records = files(root)
    records.pop('provenance.json', None)
    provenance.update(files=records, modes={name: (root / name).stat().st_mode & 0o7777 for name in records})
    (root / 'provenance.json').write_text(json.dumps(provenance, sort_keys=True, separators=(',', ':')) + '\n')


def verify(root):
    path = root / 'provenance.json'
    require(path.is_file() and not path.is_symlink(), 'prepared workspace is missing provenance.json')
    provenance = json.loads(path.read_text())
    actual = files(root)
    actual.pop('provenance.json')
    require(actual == provenance['files'], 'prepared workspace file contents changed')
    require({name: (root / name).stat().st_mode & 0o7777 for name in actual} == provenance['modes'],
            'prepared workspace permissions changed')
    return provenance


def prepare_demo_sdk(root, arch=None):
    requirements = root / 'test/demo/requirements.txt'
    require(requirements.is_file() and not requirements.is_symlink(), 'missing prepared Demo SDK requirements')
    arch = arch or platform.machine()
    lock = root / 'test/demo/requirements.lock'
    wheelhouse = root / 'test/demo/wheels' / arch
    manifest = demo_wheels.validate(wheelhouse, lock, requirements, arch)
    require(f'{sys.version_info.major}.{sys.version_info.minor}' == manifest['python'], 'Demo SDK requires prepared Python 3.12 wheels')
    site = root / 'fixtures/demo-sdk'
    require(not site.exists() and not site.is_symlink(), 'Demo SDK fixture already exists')
    subprocess.run([sys.executable, '-m', 'pip', '--isolated', '--no-input',
                    '--disable-pip-version-check', '--no-cache-dir', 'install',
                    '--only-binary=:all:', '--no-compile', '--ignore-installed', '--require-hashes',
                    '--no-index', '--find-links', str(wheelhouse),
                    '--target', str(site), '--requirement', str(lock)], check=True)
    require((site / 'e2b').is_dir(), 'prepared Demo SDK is missing e2b')
    subprocess.run([sys.executable, '-I', '-S', '-B', '-c',
                    'import sys; sys.path.insert(0, sys.argv[1]); import e2b', str(site)], check=True)
    records = files(site)
    require(records and not any('__pycache__' in Path(name).parts for name in records),
            'Demo SDK must contain wheel inputs without generated bytecode')
    return {'directory': str(site.relative_to(root)), 'requirements_sha256': digest(requirements),
            'python': manifest['python'], 'wheelhouse': manifest, 'files': records}


def image_id(path, go_arch):
    with tarfile.open(path) as archive:
        manifests = json.load(archive.extractfile('manifest.json'))
        require(len(manifests) == 1, 'fixture must describe exactly one image')
        name = manifests[0]['Config']
        require(not Path(name).is_absolute() and '..' not in Path(name).parts, 'unsafe image configuration path')
        data = archive.extractfile(name).read()
        config = json.loads(data)
        require(config['architecture'] == go_arch and config['os'] == 'linux', 'fixture has the wrong image platform')
        return 'sha256:' + hashlib.sha256(data).hexdigest()


def fixture_helper(root, owner, name):
    path = root / 'test/e2e/lib' / owner / name
    require(path.is_file() and not path.is_symlink(), f'missing prepared {owner} fixture helper')
    return path


def prepare_fixtures(root, arch, cases):
    """Prepare immutable inputs; Build/flatten/snapshot/publication stay in cases."""
    names = {Path(case).name for case in cases}
    go_arch = {'x86_64': 'amd64', 'aarch64': 'arm64'}[arch]
    target = 'linux/' + go_arch
    before = files(root)
    before_modes = {name: (root / name).stat().st_mode & 0o7777 for name in before}
    fixtures, images, python = {}, {}, {}
    for directory in ('images', 'fixtures'):
        (root / directory).mkdir(exist_ok=True)
    if 'basic.demo.sh' in names:
        require(platform.machine() == arch, 'Demo SDK preparation requires the selected native architecture')
        python['demo'] = prepare_demo_sdk(root, arch)
    if 'image.manifest.sh' in names:
        directory = root / 'fixtures/manifest'
        subprocess.run([sys.executable, '-B', str(fixture_helper(root, 'accelerator', 'manifest_fixture.py')),
                        str(directory), '--architecture', go_arch], check=True)
        for variant in ('a', 'b'):
            path = directory / f'image-{variant}.tar'
            fixtures[str(path.relative_to(root))] = {'platform': target, 'image_id': image_id(path, go_arch),
                                                     'sha256': digest(path), 'owner': 'accelerator'}
    if names & {'image.flatten.sh', 'image.registry.sh'}:
        path = root / 'images/guest-runtime.tar'
        reference = 'kuasar-e2e-guest-runtime:' + arch
        subprocess.run([sys.executable, '-B', str(fixture_helper(root, 'guest-runtime', 'fixture.py')), str(path),
                        '--tag', reference, '--architecture', go_arch], check=True)
        images['guest-runtime'] = {'reference': reference, 'platform': target, 'image_id': image_id(path, go_arch),
                                  'archive': str(path.relative_to(root)), 'sha256': digest(path), 'owner': 'guest-runtime'}
    orchestrator = any(name.startswith(('orchestrator.', 'builder.')) for name in names)
    orchestrator |= bool(names & {'telemetry.backends.sh', 'telemetry.guest.sh', 'telemetry.proxy.sh'})
    sandbox = any(name.startswith(('sandbox.', 'snapshot.', 'telemetry.')) for name in names)
    sandbox |= bool(names & {'network.tapfd.sh', 'image.manifest-boot.sh', 'image.sandbox-assembly.sh'})
    references = {}
    if orchestrator or sandbox or 'basic.demo.sh' in names:
        references['python'] = 'python:3.12-slim'
    if sandbox:
        references['busybox'] = 'busybox:latest'
    if 'telemetry.backends.sh' in names:
        references.update(BACKENDS)
    with tempfile.TemporaryDirectory(prefix='e2e-docker-') as config:
        environment = {**os.environ, 'DOCKER_CONFIG': config, 'PYTHONDONTWRITEBYTECODE': '1'}
        def save(label, reference, owner):
            path = root / 'images' / (label + '.tar')
            record = json.loads(subprocess.check_output(['docker', 'image', 'inspect', reference], env=environment))[0]
            subprocess.run(['docker', 'image', 'save', '--output', str(path), reference], env=environment, check=True)
            require(image_id(path, go_arch) == record['Id'], 'saved image differs from resolved input')
            images[label] = {'reference': reference, 'platform': target, 'image_id': record['Id'],
                             'archive': str(path.relative_to(root)), 'sha256': digest(path), 'owner': owner}
        for label, reference in references.items():
            subprocess.run(['timeout', '3m', 'docker', 'pull', '--platform=' + target, reference], env=environment, check=True)
            save(label, reference, 'platform')
        if orchestrator:
            require(platform.machine() == arch == 'x86_64', 'orchestrator image preparation requires native x86')
            for variant in ('base', 'execute'):
                label = 'orchestrator-' + variant
                reference = 'kuasar-e2e-' + label + ':' + images['python']['image_id'].split(':')[1][:16]
                subprocess.run(['bash', str(fixture_helper(root, 'orchestrator', 'prepare_base_image.sh')),
                                images['python']['image_id'], reference, variant], env=environment, check=True)
                save(label, reference, 'orchestrator')
    after = files(root)
    require(all(after.get(name) == value and (root / name).stat().st_mode & 0o7777 == before_modes[name]
                for name, value in before.items()), 'fixture preparation modified existing inputs')
    allowed = set(fixtures) | {record['archive'] for record in images.values()}
    for record in python.values():
        allowed.update(str(Path(record['directory']) / name) for name in record['files'])
    require(set(after) - set(before) == allowed, 'fixture generator wrote undeclared workspace files')
    return dict(fixtures=fixtures, images=images, python=python)


def load_images(root, provenance, environment):
    for record in provenance.get('images', {}).values():
        path = root / record['archive']
        require(digest(path) == record['sha256'], 'prepared image bytes changed')
        subprocess.run(['docker', 'image', 'load', '--input', str(path)], env=environment, check=True)
        image = json.loads(subprocess.check_output(['docker', 'image', 'inspect', record['image_id']], env=environment))[0]
        require(image['Id'] == record['image_id'] and image['Os'] + '/' + image['Architecture'] == record['platform'],
                'loaded image differs from prepared platform/digest')


def case_environment(root, provenance, case):
    environment = dict(BIN=str(root / 'bin'), E2E_WORKSPACE=str(root), E2E_ARCH=provenance['arch'],
                       E2E_LIB=str(root / 'test/e2e/lib'), PYTHONDONTWRITEBYTECODE='1', KUASAR_ARTIFACT_E2E='1',
                       TARGET_ARCH=provenance['arch'], MANIFEST_FIXTURE_DIR=str(root / 'fixtures/manifest'))
    for name, variable in HELPERS.items():
        if name in provenance.get('helpers', {}):
            environment[variable] = str(root / 'fixtures/bin' / name)
    if provenance.get('embedded', {}).get('init'):
        environment['KUASAR_EXPECTED_RUNTIME_INIT_SHA256'] = provenance['embedded']['init']
    images = provenance.get('images', {})
    for label, variable in IMAGE_VARIABLES.items():
        if label in images:
            environment[variable] = images[label]['image_id']
    label = 'guest-runtime' if case in {'image.flatten.sh', 'image.registry.sh'} else 'python'
    if label in images:
        environment.update(E2E_IMAGE=images[label]['image_id'], IMAGE=images[label]['image_id'])
    return environment
