#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 7 ]; then
    echo "usage: assemble.sh OUTPUT PLATFORM ACCELERATOR CONNECTOR GUEST_RUNTIME SANDBOXER ORCHESTRATOR" >&2
    exit 2
fi

OUTPUT="$1"
PLATFORM="$2"
shift 2
COMPONENTS=(accelerator connector guest-runtime sandboxer orchestrator)
SOURCES=("$@")

[ ! -e "$OUTPUT" ] || {
    echo "platform content output already exists: $OUTPUT" >&2
    exit 1
}
if [ ! -d "$PLATFORM/docs" ] || [ ! -d "$PLATFORM/test" ]; then
    echo "platform source is missing docs/ or test/" >&2
    exit 1
fi

mkdir -p "$OUTPUT"
cp -a "$PLATFORM/test" "$OUTPUT/"
rm -rf "$OUTPUT/test/e2e"
mkdir -p "$OUTPUT/test/e2e"
install -m 0755 "$PLATFORM/test/e2e/run_all.sh" "$OUTPUT/test/e2e/run_all.sh"
install -m 0755 "$PLATFORM/test/e2e/e2e" "$OUTPUT/test/e2e/e2e"
cp -a "$PLATFORM/test/e2e/lib" "$OUTPUT/test/e2e/lib"
mkdir -p "$OUTPUT/test/e2e/cases"

copy_cases() {
    local owner=$1 source_suite=$2 case target
    [ -d "$source_suite/cases" ] || return 0
    while IFS= read -r -d '' case; do
        target="$OUTPUT/test/e2e/cases/${case##*/}"
        [ ! -e "$target" ] || {
            echo "duplicate E2E case id from $owner: ${case##*/}" >&2
            exit 1
        }
        install -m 0755 "$case" "$target"
    done < <(find "$source_suite/cases" -maxdepth 1 -type f -name '*.*.sh' -print0 | sort -z)
}

# Temporary #172 release boundary: migrated owners no longer ship run_all.sh,
# while legacy owners still do. Generate only the old owner entry point from
# that owner's exact case IDs; the canonical test/e2e/e2e runner remains the
# sole case executor. Remove this shim when every owner is case-only.
generate_case_runner() {
    local owner=$1 source_suite=$2
    python3 - "$owner" "$source_suite/cases" \
        "$OUTPUT/test/e2e/$owner/run_all.sh" \
        "$(dirname "${BASH_SOURCE[0]}")/../../ci/integration" <<'PY'
from pathlib import Path
import shlex
import sys

sys.path.insert(0, sys.argv[4])
from artifacts import case_name

owner, source, target = sys.argv[1:4]
cases = sorted(Path(source).glob("*.sh"))
if not cases:
    raise SystemExit(
        f"{owner} source is missing valid test/e2e/cases/*.sh and executable test/e2e/run_all.sh"
    )
for case in cases:
    case_name(case.name)
    if not case.is_file():
        raise SystemExit(f"{owner} E2E case is not a regular file: {case.name}")

script = '''#!/usr/bin/env bash
# Generated by assemble.sh for the #172 mixed-owner transition only.
set -euo pipefail
[ "$#" -eq 0 ] || { echo "use test/e2e/e2e for case selection" >&2; exit 2; }
SUITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_ROOT="$(cd "$SUITE_DIR/../.." && pwd)"
STATE="$(mktemp -d)"
cleanup() {
    local status=$?
    if [ "$status" -eq 0 ]; then rm -rf "$STATE"; else
        echo "E2E state retained at $STATE" >&2
    fi
}
trap cleanup EXIT
WORKSPACE="${E2E_WORKSPACE:-$STATE/workspace}"
if [ -z "${E2E_WORKSPACE:-}" ]; then
    mkdir -p "$WORKSPACE/test"
    ln -s "$(cd "${BIN:-$RELEASE_ROOT/bin}" && pwd)" "$WORKSPACE/bin"
    ln -s "$SUITE_DIR" "$WORKSPACE/test/e2e"
    ln -s "$RELEASE_ROOT/fixtures" "$WORKSPACE/fixtures"
fi
export E2E_CASES_DIR="$SUITE_DIR/cases" E2E_LIB="$SUITE_DIR/lib"
python3 "$SUITE_DIR/e2e" run --workdir "$WORKSPACE" \
    --arch "${E2E_ARCH:-$(uname -m)}" --run-root "$STATE/run" --out-root "$STATE/out"'''
# Exact IDs preserve owner isolation even when owners share a suite prefix.
script += ''.join(' --include ' + shlex.quote(case.name) for case in cases) + '\n'
Path(target).write_text(script, encoding="utf-8")
Path(target).chmod(0o755)
PY
}

for index in "${!COMPONENTS[@]}"; do
    component="${COMPONENTS[$index]}"
    source_root="${SOURCES[$index]}"
    source_suite="$source_root/test/e2e"
    if [ -n "${E2E_SOURCE_ROOT:-}" ]; then
        source_suite="$E2E_SOURCE_ROOT/$component/test/e2e"
    fi
    if find "$source_suite" -type l -print -quit | grep -q .; then
        echo "$component e2e suite contains a symbolic link" >&2
        exit 1
    fi
    [ -f "$source_root/README.md" ] && [ -d "$source_root/docs" ] || {
        echo "$component source is missing README.md or docs/" >&2
        exit 1
    }
    cp -a "$source_suite" "$OUTPUT/test/e2e/$component"
    copy_cases "$component" "$source_suite"
    if [ -e "$source_suite/run_all.sh" ]; then
        [ -f "$source_suite/run_all.sh" ] && [ -x "$source_suite/run_all.sh" ] || {
            echo "$component source has non-executable test/e2e/run_all.sh" >&2
            exit 1
        }
    else
        generate_case_runner "$component" "$source_suite"
    fi
    if [ -d "$source_suite/lib" ]; then
        mkdir -p "$OUTPUT/test/e2e/lib/$component"
        cp -a "$source_suite/lib/." "$OUTPUT/test/e2e/lib/$component/"
    fi
done

platform_suite="$PLATFORM/test/e2e/platform"
[ -x "$platform_suite/run_all.sh" ] || {
    echo "platform source is missing executable test/e2e/platform/run_all.sh" >&2
    exit 1
}
if find "$platform_suite" -type l -print -quit | grep -q .; then
    echo "platform e2e suite contains a symbolic link" >&2
    exit 1
fi
cp -a "$platform_suite" "$OUTPUT/test/e2e/platform"
copy_cases platform "$platform_suite"

# Keep the existing flat design-document entry points, include both languages
# and out-of-docs guides, then rebase only documentation links for this layout.
python3 "$(dirname "${BASH_SOURCE[0]}")/assemble_docs.py" \
    "$OUTPUT" "$PLATFORM" "${SOURCES[@]}"

for component in "${COMPONENTS[@]}" platform; do
    [ -x "$OUTPUT/test/e2e/$component/run_all.sh" ] || {
        echo "assembled suite is missing executable $component/run_all.sh" >&2
        exit 1
    }
done
[ -x "$OUTPUT/test/e2e/e2e" ] || { echo "assembled suite is missing unified E2E runner" >&2; exit 1; }
[ -f "$OUTPUT/test/e2e/lib/common.sh" ] || { echo "assembled suite is missing common E2E helpers" >&2; exit 1; }
[ ! -e "$OUTPUT/test/e2e/assemble.sh" ] || {
    echo "source-only E2E assembler leaked into deliverable content" >&2
    exit 1
}
